# Generated by Django 2.2 on 2019-04-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish_text', models.TextField()),
                ('wish_owner', models.CharField(max_length=50)),
                ('shown', models.BooleanField()),
            ],
        ),
    ]
