# Generated by Django 2.2 on 2019-04-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishbook', '0002_wish_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='shown',
            field=models.BooleanField(default=True),
        ),
    ]
