# Generated by Django 2.2 on 2019-04-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishbook', '0003_auto_20190419_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='wish_owner',
            field=models.CharField(max_length=50, verbose_name='ชื่อผู้อวยพร'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='wish_text',
            field=models.CharField(max_length=240, verbose_name='ข้อความอวยพร'),
        ),
    ]
